### ISSUE TITLE
Use CommandBuilder instead of string for $

### ISSUE THREAD

**Issue by sigmaSd** [impactaky/dax_extras#1]
I think the earlier prototype where $ (pipe function) accepts a CommandBuilder instead of a string is better  because its more flexible

**Comment by sigmaSd** [comment]
Not sure how better is it honestly

**Comment by impactaky** [comment]
Can I assume that this issue will be resolved now that CommandBuilder can be passed to pipe in #15?

**Comment by sigmaSd** [comment]
yes
