### ISSUE TITLE
Refactor this module api

### ISSUE THREAD

**Issue by sigmaSd** [impactaky/dax_extras#2]
I personally prefer doing this
```
import {$} from dax
import {} from "https://raw.githubusercontent.com/impactaky/dax_extras/1.0.0/mod.ts"; // adds extra stuff
```
Not 100% sure about the api, maybe when importing like the above it will update `$` with the extra commands, maybe thats reasonable

Personally I prefer that instead of the current apporach where this module takes the place of dax, since it will allow other ppl to publish extra stuff and in theory they can all work together by importing them after dax

**Comment by sigmaSd** [comment]
though maybe its weird since you're already depending on dax

**Comment by impactaky** [comment]
Thank you! 
I tried, but it did not work if the version imported by dax_extras and the version imported by user script are different. 
Do you have any good ideas on this point?

**Comment by sigmaSd** [comment]
Nope I tried as well it didn't work, I thought maybe you have more ideas xD

I'll keep asking around , if really there is no solution I think I'll just close this

**Comment by sigmaSd** [comment]
In theory it should work, because a minimal example works indeed

a.ts
```ts
export class A {
}
```
b.ts
```ts
import { A } from "./a.ts";

declare module "./a.ts" {
  interface A {
    b(): void;
  }
}

A.prototype.b = () => {};
```
c.ts
```ts
import { A } from "./a.ts";
import "./b.ts";

new A().b(); 
```

**Comment by sigmaSd** [comment]
oh I just noticed what you mean (it didn't work at all earlier for me)

ok now I'm on the same page I'll look for ideas for versioning

**Comment by sigmaSd** [comment]
another avenue to think about

```ts
import $ from "https://deno.land/x/dax@0.32.0/mod.ts";
import { addExtras } from "./vendor/raw.githubusercontent.com/impactaky/dax_extras/1.0.0/mod.ts";

const $$ = addExtras($);

const stream = $$`echo "abc\nabcde\nabcdef\nbcdefg"`
  .map((l) => `bug : ${l}`)
  .$(`grep 'bug : a'`).noThrow()
  .filter((l) => l.length > "bug : ".length + 3)
  .xargs((l) => $$`echo de${l}`);
```
where addExtras is something like
```ts
export function addExtras<T>(e: T): T {
  e.prototype.xargs = function (
    xargsFunction: XargsFunction,
  ) {
    return this.lineStream().xargs(xargsFunction);
  };
  return e;
}
```
also this can handle versioning, since I can file a pr to dax to add its version metadata somewhere, so we can check it and have some semver checks on it

**Comment by sigmaSd** [comment]
hmm I like this variation actually seems to fix all issues 
```ts
import $ from "https://deno.land/x/dax@0.32.0/mod.ts";
import { addExtras } from "./vendor/raw.githubusercontent.com/impactaky/dax_extras/1.0.0/mod.ts";

addExtras($); // this will mutate it in place

const stream = $`echo "abc\nabcde\nabcdef\nbcdefg"`
  .map((l) => `bug : ${l}`)
  .$(`grep 'bug : a'`).noThrow()
  .filter((l) => l.length > "bug : ".length + 3)
  .xargs((l) => $`echo de${l}`);
```

**Comment by impactaky** [comment]
Looks very good!

**Comment by sigmaSd** [comment]
maybe dax can expose $.version that we can use to check if its semver compatible with this module for example `semver.gt_or_eq($.version,0.32)`

**Comment by sigmaSd** [comment]
I'm trying to implement this, but no success yet though  I'm getting close
```ts
import type { $Type } from "https://deno.land/x/dax@0.32.0/mod.ts";

interface Q extends $Type {
  pipe(): ReadableStream<Uint8Array>;
  lineStream(): LineStream;
  $(next: string): CommandBuilder;
  map(mapFunction: MapFunction<string, string>): LineStream;
  filter(filterFunction: FilterFunction<string>): LineStream;
  xargs(xargsFunction: XargsFunction): Promise<CommandChild[]>;
}

function addExtras($: $Type): asserts $ is Q {
  ($ as Q).pipe = function () {
    return this.stdout("piped").spawn().stdout(); // !!!!!!!!!!!!!!! this line fails !!!!!!!!!!!!!!!!
  };

  ($ as Q).lineStream = function () {
    return new LineStream(
      this.pipe().pipeThrough(new TextDecoderStream())
        .pipeThrough(new TextLineStream()),
    );
  };
```
`this.stdout` fails because that function is implemented on `CommandBuilder` not `$`

**Comment by sigmaSd** [comment]
also another thing to look at is this part (custom $)  https://github.com/dsherret/dax#custom-

**Comment by sigmaSd** [comment]
@impactaky I think a pragmatic approach , is to append the dax version used internally to the dax-extras version (this is allowed by semver for metadata tags)

This way dax-extras can bump its version as normal, while always showing the user which dax version they need to use
so some thing like
```
0.1.0-0.32.0
0.2.0-0.32.0
0.3.0-0.33.0
```

This requires just 2 things
- publishing this module to deno.land with a version in that format
- updating the readme to show something like

```md
### Use with your dax extends

You can import dax_extras like this.

```typescript
import $ from "https://deno.land/x/dax@0.32.0/mod.ts";
// the dax version used internally by dax extras is at the suffix
// it **must** match the dax version used
import "https://deno.land/x/dax_extras@0.1.0-0.32.0/mod.ts";
```



I think that looks really better from the user/api perspective, and we can only keep this method documented in the readme
so we can remove docs showing direct import (`import $ from "https://deno.land/x/dax_extras/mod.ts";`)

**Comment by sigmaSd** [comment]
fixed in https://github.com/impactaky/dax_extras/pull/25
